# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f7356f7ef18ff74fac3de6c94c3014911c394487e60e226b9af0e29aaeb7394cb557b562a886e0ef10e84a9be7e8445751b924b7dcd41202df864fec697a970

test:
  secret_key_base: e646c463d36f5b15d2fe9f9366e66c098e17d6398d8933bb89b440f07dae5583545bb45e5e8114295766a6ec2d89e7a3ec328ad9984ddf0a7efd498b3809fc0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
